import type { Metadata } from "next"
import { Geist, Geist_Mono, Quicksand } from "next/font/google"
import "./globals.css"
import Providers from "@/components/providers"
import { Sidebar } from "@/components/layout/sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full">
        <Providers>
          <Sidebar className="w-80" />
          <div className="w-80"></div>
          <div className="flex-1">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
